export const enLabels = {
  ext: "ext.",
  country: "Phone number country",
  phone: "Phone",
  AB: "Abkhazia",
  AC: "Ascension Island",
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei Darussalam",
  BO: "Bolivia",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Congo, Democratic Republic of the",
  CF: "Central African Republic",
  CG: "Congo",
  CH: "Switzerland",
  CI: "Cote d'Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Federated States of Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin (French Part)",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Burma",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  OS: "South Ossetia",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Swaziland",
  TA: "Tristan da Cunha",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Holy See (Vatican City State)",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  XK: "Kosovo",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  ZZ: "International",
};

export const arLab = {
  ext: "ext.",
  country: "Phone number country",
  phone: "Phone",
  AB: "أبخازيا",
  AC: "جزيرة أسنسيون",
  AD: "أندورا",
  AE: "الإمارات العربية المتحدة",
  AF: "أفغانستان",
  AG: "أنتيغوا وبربودا",
  AI: "أنغيلا",
  AL: "ألبانيا",
  AM: "أرمينيا",
  AO: "أنغولا",
  AQ: "أنتاركتيكا",
  AR: "الأرجنتين",
  AS: "ساموا الأمريكية",
  AT: "النمسا",
  AU: "أستراليا",
  AW: "أروبا",
  AX: "جزر آلاند",
  AZ: "أذربيجان",
  BA: "البوسنة والهرسك",
  BB: "بربادوس",
  BD: "بنغلادش",
  BE: "بلجيكا",
  BF: "بوركينا فاسو",
  BG: "بلغاريا",
  BH: "البحرين",
  BI: "بوروندي",
  BJ: "بنين",
  BL: "سانت بارتيليمي",
  BM: "برمودا",
  BN: "بروناي دار السلام",
  BO: "بوليفيا",
  BQ: "بونير وسانت يوستاتيوس وسابا",
  BR: "البرازيل",
  BS: "جزر البهاما",
  BT: "بوتان",
  BV: "جزيرة بوفيت",
  BW: "بوتسوانا",
  BY: "بيلاروسيا",
  BZ: "بليز",
  CA: "كندا",
  CC: "جزر كوكوس (كيلينغ)",
  CC: "جمهورية الكونغو الديموقراطية",
  CF: "جمهورية أفريقيا الوسطى",
  CG: "الكونغو",
  CH: "سويسرا",
  CI: "كوت ديفوار",
  CK: "جزر كوك",
  CL: "شيلي",
  CM: "الكاميرون",
  CN: "الصين",
  CO: "كولومبيا",
  CR: "كوستاريكا",
  CU: "كوبا",
  CV: "الرأس الأخضر",
  CW: "كوراساو",
  CX: "جزيرة الكريسماس",
  CY: "قبرص",
  CZ: "جمهورية التشيك",
  DE: "ألمانيا",
  DJ: "جيبوتي",
  DK: "الدنمارك",
  DM: "دومينيكا",
  DO: "جمهورية الدومينيكان",
  DZ: "الجزائر",
  EC: "الإكوادور",
  EE: "إستونيا",
  EG: "مصر",
  EH: "الصحراء الغربية",
  ER: "إريتريا",
  ES: "أسبانيا",
  ET: "إثيوبيا",
  FI: "فنلندا",
  FJ: "فيجي",
  FK: "جزر فوكلاند",
  FM: "ولايات ميكرونيزيا الموحدة",
  FO: "جزر فارو",
  FR: "فرنسا",
  GA: "غابون",
  GB: "المملكة المتحدة",
  GD: "غرينادا",
  GE: "جورجيا",
  GF: "غيانا الفرنسية",
  GG: "غيرنسي",
  GH: "غانا",
  GI: "جبل طارق",
  GL: "جرينلاند",
  GM: "غامبيا",
  GN: "غينيا",
  GP: "جوادلوب",
  GQ: "غينيا الاستوائية",
  GR: "اليونان",
  GS: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
  GT: "جواتيمالا",
  GU: "غوام",
  GW: "غينيا بيساو",
  GY: "غيانا",
  HK: "هونج كونج",
  HM: "جزيرة القلب و جزر ماكدونالد",
  HN: "هندوراس",
  HR: "كرواتيا",
  HT: "هايتي",
  HU: "المجر",
  ID: "إندونيسيا",
  IE: "إيرلاندا",
  IL: "إسرائيل",
  IM: "جزيرة مان",
  IN: " الهند",
  IO: "إقليم المحيط الهندي البريطاني",
  IQ: "العراق",
  IR: "إيران",
  IS: "أيسلندا",
  IT: "إيطاليا",
  JE: "جيرسي",
  JM: "جامايكا",
  JO: "الأردن",
  JP: "اليابان",
  KE: "كينيا",
  KG: "قيرغيزستان",
  KH: "كمبوديا",
  KI: "كيريباتي",
  KM: "جزر القمر",
  KN: "سانت كيتس ونيفيس",
  KP: "كوريا الشمالية",
  KR: "كوريا الجنوبية",
  KW: "الكويت",
  KY: "جزر كايمان",
  KZ: "كازاخستان",
  LA: "لاوس",
  LB: "لبنان",
  LC: "سانت لوسيا",
  LI: "ليختنشتاين",
  LK: "سريلانكا",
  LR: "ليبيريا",
  LS: "ليسوتو",
  LT: "ليتوانيا",
  LU: "لوكسمبورغ",
  LV: "لاتفيا",
  LY: "ليبيا",
  MA: "المغرب",
  MC: "موناكو",
  MD: "مولدوفا",
  ME: "الجبل الأسود",
  MF: "سانت مارتن (الجزء الفرنسي)",
  MG: "مدغشقر",
  MH: "جزر مارشال",
  MK: "مقدونيا الشمالية",
  ML: "مالي",
  MM: "بورما",
  MN: "منغوليا",
  MO: "ماكاو",
  MP: "جزر ماريانا الشمالية",
  MQ: "مارتينيك",
  MR: "موريتانيا",
  MS: "مونتسيرات",
  MT: "مالطا",
  MU: "موريشيوس",
  MV: "جزر المالديف",
  MW: "ملاوي",
  MX: "المكسيك",
  MY: "ماليزيا",
  MZ: "موزامبيق",
  NA: "ناميبيا",
  NC: "كاليدونيا الجديدة",
  NE: "النيجر",
  NF: "جزيرة نورفولك",
  NG: "نيجيريا",
  NI: "نيكاراغوا",
  NL: "هولندا",
  NO: "النرويج",
  NP: "نيبال",
  NR: "ناورو",
  NU: "نيوي",
  NZ: "نيوزيلندا",
  OM: "عمان",
  OS: "أوسيتيا الجنوبية",
  PA: "بنما",
  PE: "بيرو",
  PF: "بولينيزيا الفرنسية",
  PG: "بابوا غينيا الجديدة",
  PH: "الفلبين",
  PK: "باكستان",
  PL: "بولندا",
  PM: "سانت بيير وميكلون",
  PN: "بيتكيرن",
  PR: "بورتوريكو",
  PS: "فلسطين",
  PT: "البرتغال",
  PW: "بالاو",
  PY: "باراغواي",
  QA: "قطر",
  RE: "ريونيون",
  RO: "رومانيا",
  RS: "صربيا",
  RU: "روسيا",
  RW: "رواندا",
  SA: "المملكة العربية السعودية",
  SB: "جزر سليمان",
  SC: "سيشيل",
  SD: "السودان",
  SE: "السويد",
  SG: "سنغافورة",
  SH: "سانت هيلانة",
  SI: "سلوفينيا",
  SJ: "سفالبارد وجان ماين",
  SK: "سلوفاكيا",
  SL: "سيراليون",
  SM: "سان مارينو",
  SN: "السنغال",
  SO: "الصومال",
  SR: "سورينام",
  SS: "جنوب السودان",
  ST: "ساو تومي وبرينسيبي",
  SV: "السلفادور",
  SX: "سينت مارتن",
  SY: "سوريا",
  SZ: "سوازيلاند",
  TA: "تريستان دا كونها",
  TC: "جزر تركس وكايكوس",
  TD: "تشاد",
  TF: "الأقاليم الجنوبية الفرنسية",
  TG: "توغو",
  TH: "تايلاند",
  TJ: "طاجيكستان",
  TK: "توكيلاو",
  TL: "تيمور - ليشتي",
  TM: "تركمانستان",
  TN: "تونس",
  TO: "تونغا",
  TR: "تركيا",
  TT: "ترينيداد وتوباغو",
  TV: "توفالو",
  TW: "تايوان",
  TZ: "تنزانيا",
  UA: "أوكرانيا",
  UG: "أوغندا",
  UM: "جزر الولايات المتحدة الصغيرة النائية",
  US: "الولايات المتحدة الأمريكية",
  UY: "أوروغواي",
  UZ: "أوزبكستان",
  VA: "دولة الفاتيكان",
  VC: "سانت فنسنت وجزر غرينادين",
  VE: "فنزويلا",
  VG: "جزر فيرجن البريطانية",
  VI: "جزر فيرجن , الولايات المتحدة",
  VN: "فيتنام",
  VU: "فانواتو",
  WF: "واليس وفوتونا",
  WS: "ساموا",
  XK: "كوسوفو",
  YE: "اليمن",
  YT: "مايوت",
  ZA: "جنوب أفريقيا",
  ZM: "زامبيا",
  ZW: "زمبابوي",
  ZZ: "دولي",
};
