export const pagination = (displayedContent, itemsNum, pageNum) => {
  const count = Math.ceil(displayedContent?.length / itemsNum);
  const startIndex = (pageNum - 1) * itemsNum;
  const requiredArr =
    displayedContent?.length &&
    displayedContent?.slice(startIndex, startIndex + itemsNum);
  return { count, requiredArr };
};

export const dynamicDataPagination = (itemsNum, pageNum) => {
  let startIndex = (pageNum - 1) * itemsNum;
  return { startIndex };
};

export const getFileM = (files, isRTL) => {
  const file = files?.find((item) => {
    const { publishMode, mimetype } = item;
    const isFile = mimetype?.split("/")[0] === "application" ? true : false;

    if (isRTL && item && publishMode === 2 && isFile) return true;
    else return false;
  });

  return {
    uuid: file?.uuid,
    alt: file?.title ? file?.title.en || file?.title.ar : null,
    readCount: file?.readCount,
    downloadCount: file?.downloadCount,
    fileId: file?.id,
  };
};

export const getFiles = (files, isRTL) => {
  let fileObjects = [];
  files.find((file) => {
    if (file) {
      const { publishMode, mimetype } = file;
      if (
        isRTL &&
        publishMode === 1 &&
        mimetype.split("/")[0] === "application"
      )
        fileObjects = [
          ...fileObjects,
          {
            uuid: file.uuid || "",
            alt: !isRTL ? file?.title?.en || "" : file?.title?.ar || "",
          },
        ];

      if (
        !isRTL &&
        publishMode === 2 &&
        mimetype.split("/")[0] === "application"
      )
        fileObjects = [
          ...fileObjects,
          {
            uuid: file.uuid || "",
            alt: !isRTL ? file?.title?.en || "" : file?.title?.ar || "",
          },
        ];
    }
  });
  return fileObjects;
};

export const getImage = (files, isRTL) => {
  const image = files?.find((file) => {
    // const { publishMode, mimetype } = file;
    const isImage = file?.mimetype?.split("/")[0] === "image" ? true : false;

    if (isRTL && file && file?.publishMode === 1 && isImage) return true;
    else if (!isRTL && file && file?.publishMode === 2 && isImage) return true;
    else if (file && file?.publishMode === 3 && isImage) return true;
    else return false;
  });

  return {
    uuid: image?.uuid,
    alt: image?.alt ? image?.alt.en || image?.alt.ar : null,
  };
};

export const getImages = (files, isRTL) => {
  let imageObjects = [];
  files.find((file) => {
    if (file) {
      const { publishMode, mimetype } = file;

      if (isRTL && publishMode === 1 && mimetype.split("/")[0] === "image")
        imageObjects = [
          ...imageObjects,
          {
            uuid: file.uuid || "",
            alt: file.alt.en || file.alt.ar || "",
          },
        ];
      else if (
        !isRTL &&
        publishMode === 2 &&
        mimetype.split("/")[0] === "image"
      )
        imageObjects = [
          ...imageObjects,
          {
            uuid: file.uuid || "",
            alt: file.alt.en || file.alt.ar || "",
          },
        ];
      else if (
        !isRTL &&
        publishMode === 3 &&
        mimetype.split("/")[0] === "image"
      )
        imageObjects = [
          ...imageObjects,
          {
            uuid: file.uuid || "",
            alt: file.alt.en || file.alt.ar || "",
          },
        ];
    }
  });
  return imageObjects;
};

export const getFile = (files, isRTL) => {
  const file = files?.find((item) => {
    let result = false;
    const { publishMode, mimetype } = item;
    const isFile = mimetype?.split("/")[0] === "application" ? true : false;

    if (item && !isRTL && publishMode === 2 && isFile) result = true;
    if (item && isRTL && publishMode === 1 && isFile) result = true;
    return result;
  });
  return {
    uuid: file?.uuid,
    alt: file?.title ? file?.title.en || file?.title.ar : null,
    readCount: file?.viewed,
    downloadCount: file?.downloaded,
    fileId: file?.id,
  };
};

export const isFile = (file) => {
  const { mimetype } = file;
  return mimetype?.split("/")[0] === "application";
};

export const isImage = (image) => {
  const { mimetype } = image;
  return mimetype?.split("/")[0] === "image";
};

export const getFileUrl = async (fileName) => {
  return fetch(`/api/file/download/${fileName}`)
    .then((res) => res.blob())
    .then((res) => URL.createObjectURL(res))
    .catch((e) => console.log(e));
};

export const Countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia (Hrvatska)",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "France Metropolitan",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and Mc Donald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao, People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia, The Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia (Slovak Republic)",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "St. Helena",
  "St. Pierre and Miquelon",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Yugoslavia",
  "Zambia",
  "Zimbabwe",
  "Palestine",
];
export const Emirates = [
  "Abu Dhabi",
  "Dubai",
  "Sharjah",
  "Ajman",
  "Umm Al Quwain",
  "Ras Al Khaimah",
  "Fujairah",
];
export const ArabicEmirates = [
  "أبو ظبي",
  "دبي",
  "الشارقة",
  "عجمان",
  "أم القيوين",
  "رأس الخيمة",
  "الفجيرة",
];
export const enLabels = {
  ext: "ext.",
  country: "Phone number country",
  phone: "Phone",
  AB: "Abkhazia",
  AC: "Ascension Island",
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei Darussalam",
  BO: "Bolivia",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Congo, Democratic Republic of the",
  CF: "Central African Republic",
  CG: "Congo",
  CH: "Switzerland",
  CI: "Cote d'Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Federated States of Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin (French Part)",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Burma",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  OS: "South Ossetia",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Swaziland",
  TA: "Tristan da Cunha",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Holy See (Vatican City State)",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  XK: "Kosovo",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  ZZ: "International",
};

export const arLabels = {
  ext: "ext.",
  country: "Phone number country",
  phone: "Phone",
  AB: "أبخازيا",
  AC: "جزيرة أسنسيون",
  AD: "أندورا",
  AE: "الإمارات العربية المتحدة",
  AF: "أفغانستان",
  AG: "أنتيغوا وبربودا",
  AI: "أنغيلا",
  AL: "ألبانيا",
  AM: "أرمينيا",
  AO: "أنغولا",
  AQ: "أنتاركتيكا",
  AR: "الأرجنتين",
  AS: "ساموا الأمريكية",
  AT: "النمسا",
  AU: "أستراليا",
  AW: "أروبا",
  AX: "جزر آلاند",
  AZ: "أذربيجان",
  BA: "البوسنة والهرسك",
  BB: "بربادوس",
  BD: "بنغلادش",
  BE: "بلجيكا",
  BF: "بوركينا فاسو",
  BG: "بلغاريا",
  BH: "البحرين",
  BI: "بوروندي",
  BJ: "بنين",
  BL: "سانت بارتيليمي",
  BM: "برمودا",
  BN: "بروناي دار السلام",
  BO: "بوليفيا",
  BQ: "بونير وسانت يوستاتيوس وسابا",
  BR: "البرازيل",
  BS: "جزر البهاما",
  BT: "بوتان",
  BV: "جزيرة بوفيت",
  BW: "بوتسوانا",
  BY: "بيلاروسيا",
  BZ: "بليز",
  CA: "كندا",
  CC: "جزر كوكوس (كيلينغ)",
  CC: "جمهورية الكونغو الديموقراطية",
  CF: "جمهورية أفريقيا الوسطى",
  CG: "الكونغو",
  CH: "سويسرا",
  CI: "كوت ديفوار",
  CK: "جزر كوك",
  CL: "شيلي",
  CM: "الكاميرون",
  CN: "الصين",
  CO: "كولومبيا",
  CR: "كوستاريكا",
  CU: "كوبا",
  CV: "الرأس الأخضر",
  CW: "كوراساو",
  CX: "جزيرة الكريسماس",
  CY: "قبرص",
  CZ: "جمهورية التشيك",
  DE: "ألمانيا",
  DJ: "جيبوتي",
  DK: "الدنمارك",
  DM: "دومينيكا",
  DO: "جمهورية الدومينيكان",
  DZ: "الجزائر",
  EC: "الإكوادور",
  EE: "إستونيا",
  EG: "مصر",
  EH: "الصحراء الغربية",
  ER: "إريتريا",
  ES: "أسبانيا",
  ET: "إثيوبيا",
  FI: "فنلندا",
  FJ: "فيجي",
  FK: "جزر فوكلاند",
  FM: "ولايات ميكرونيزيا الموحدة",
  FO: "جزر فارو",
  FR: "فرنسا",
  GA: "غابون",
  GB: "المملكة المتحدة",
  GD: "غرينادا",
  GE: "جورجيا",
  GF: "غيانا الفرنسية",
  GG: "غيرنسي",
  GH: "غانا",
  GI: "جبل طارق",
  GL: "جرينلاند",
  GM: "غامبيا",
  GN: "غينيا",
  GP: "جوادلوب",
  GQ: "غينيا الاستوائية",
  GR: "اليونان",
  GS: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
  GT: "جواتيمالا",
  GU: "غوام",
  GW: "غينيا بيساو",
  GY: "غيانا",
  HK: "هونج كونج",
  HM: "جزيرة القلب و جزر ماكدونالد",
  HN: "هندوراس",
  HR: "كرواتيا",
  HT: "هايتي",
  HU: "المجر",
  ID: "إندونيسيا",
  IE: "إيرلاندا",
  IL: "إسرائيل",
  IM: "جزيرة مان",
  IN: " الهند",
  IO: "إقليم المحيط الهندي البريطاني",
  IQ: "العراق",
  IR: "إيران",
  IS: "أيسلندا",
  IT: "إيطاليا",
  JE: "جيرسي",
  JM: "جامايكا",
  JO: "الأردن",
  JP: "اليابان",
  KE: "كينيا",
  KG: "قيرغيزستان",
  KH: "كمبوديا",
  KI: "كيريباتي",
  KM: "جزر القمر",
  KN: "سانت كيتس ونيفيس",
  KP: "كوريا الشمالية",
  KR: "كوريا الجنوبية",
  KW: "الكويت",
  KY: "جزر كايمان",
  KZ: "كازاخستان",
  LA: "لاوس",
  LB: "لبنان",
  LC: "سانت لوسيا",
  LI: "ليختنشتاين",
  LK: "سريلانكا",
  LR: "ليبيريا",
  LS: "ليسوتو",
  LT: "ليتوانيا",
  LU: "لوكسمبورغ",
  LV: "لاتفيا",
  LY: "ليبيا",
  MA: "المغرب",
  MC: "موناكو",
  MD: "مولدوفا",
  ME: "الجبل الأسود",
  MF: "سانت مارتن (الجزء الفرنسي)",
  MG: "مدغشقر",
  MH: "جزر مارشال",
  MK: "مقدونيا الشمالية",
  ML: "مالي",
  MM: "بورما",
  MN: "منغوليا",
  MO: "ماكاو",
  MP: "جزر ماريانا الشمالية",
  MQ: "مارتينيك",
  MR: "موريتانيا",
  MS: "مونتسيرات",
  MT: "مالطا",
  MU: "موريشيوس",
  MV: "جزر المالديف",
  MW: "ملاوي",
  MX: "المكسيك",
  MY: "ماليزيا",
  MZ: "موزامبيق",
  NA: "ناميبيا",
  NC: "كاليدونيا الجديدة",
  NE: "النيجر",
  NF: "جزيرة نورفولك",
  NG: "نيجيريا",
  NI: "نيكاراغوا",
  NL: "هولندا",
  NO: "النرويج",
  NP: "نيبال",
  NR: "ناورو",
  NU: "نيوي",
  NZ: "نيوزيلندا",
  OM: "عمان",
  OS: "أوسيتيا الجنوبية",
  PA: "بنما",
  PE: "بيرو",
  PF: "بولينيزيا الفرنسية",
  PG: "بابوا غينيا الجديدة",
  PH: "الفلبين",
  PK: "باكستان",
  PL: "بولندا",
  PM: "سانت بيير وميكلون",
  PN: "بيتكيرن",
  PR: "بورتوريكو",
  PS: "فلسطين",
  PT: "البرتغال",
  PW: "بالاو",
  PY: "باراغواي",
  QA: "قطر",
  RE: "ريونيون",
  RO: "رومانيا",
  RS: "صربيا",
  RU: "روسيا",
  RW: "رواندا",
  SA: "المملكة العربية السعودية",
  SB: "جزر سليمان",
  SC: "سيشيل",
  SD: "السودان",
  SE: "السويد",
  SG: "سنغافورة",
  SH: "سانت هيلانة",
  SI: "سلوفينيا",
  SJ: "سفالبارد وجان ماين",
  SK: "سلوفاكيا",
  SL: "سيراليون",
  SM: "سان مارينو",
  SN: "السنغال",
  SO: "الصومال",
  SR: "سورينام",
  SS: "جنوب السودان",
  ST: "ساو تومي وبرينسيبي",
  SV: "السلفادور",
  SX: "سينت مارتن",
  SY: "سوريا",
  SZ: "سوازيلاند",
  TA: "تريستان دا كونها",
  TC: "جزر تركس وكايكوس",
  TD: "تشاد",
  TF: "الأقاليم الجنوبية الفرنسية",
  TG: "توغو",
  TH: "تايلاند",
  TJ: "طاجيكستان",
  TK: "توكيلاو",
  TL: "تيمور - ليشتي",
  TM: "تركمانستان",
  TN: "تونس",
  TO: "تونغا",
  TR: "تركيا",
  TT: "ترينيداد وتوباغو",
  TV: "توفالو",
  TW: "تايوان",
  TZ: "تنزانيا",
  UA: "أوكرانيا",
  UG: "أوغندا",
  UM: "جزر الولايات المتحدة الصغيرة النائية",
  US: "الولايات المتحدة الأمريكية",
  UY: "أوروغواي",
  UZ: "أوزبكستان",
  VA: "دولة الفاتيكان",
  VC: "سانت فنسنت وجزر غرينادين",
  VE: "فنزويلا",
  VG: "جزر فيرجن البريطانية",
  VI: "جزر فيرجن , الولايات المتحدة",
  VN: "فيتنام",
  VU: "فانواتو",
  WF: "واليس وفوتونا",
  WS: "ساموا",
  XK: "كوسوفو",
  YE: "اليمن",
  YT: "مايوت",
  ZA: "جنوب أفريقيا",
  ZM: "زامبيا",
  ZW: "زمبابوي",
  ZZ: "دولي",
};
export const CountriesLTR = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia (Hrvatska)",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "France Metropolitan",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and Mc Donald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao, People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia, The Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia (Slovak Republic)",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "St. Helena",
  "St. Pierre and Miquelon",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Yugoslavia",
  "Zambia",
  "Zimbabwe",
  "Palestine",
];

export const CountriesRTL = [
  "أفغانستان",
  "ألبانيا",
  "الجزائر",
  "ساموا الأمريكية",
  "أندورا",
  "أنغولا",
  "أنغيلا",
  "أنتاركتيكا",
  "أنتيغوا وبربودا",
  "الأرجنتين",
  "أرمينيا",
  "أروبا",
  "أستراليا",
  "النمسا",
  "أذربيجان",
  "جزر البهاما",
  "البحرين",
  "بنغلاديش",
  "بربادوس",
  "بيلاروسيا",
  "بلجيكا",
  "بليز",
  "بنن",
  "برمودا",
  "بوتان",
  "بوليفيا",
  "البوسنة والهرسك",
  "بوتسوانا",
  "جزيرة بوفيت",
  "البرازيل",
  "إقليم المحيط البريطاني الهندي",
  "بروناي دار السلام",
  "بلغاريا",
  "بوركينا فاسو",
  "بوروندي",
  "كمبوديا",
  "الكاميرون",
  "كندا",
  "الرأس الأخضر",
  "جزر كايمان",
  "جمهورية افريقيا الوسطى",
  "تشاد",
  "شيلي",
  "الصين",
  "جزيرة الكريسماس",
  "جزر كوكوس (كيلينغ)",
  "كولومبيا",
  "جزر القمر",
  "الكونغو",
  "جمهورية الكونغو الديمقراطية",
  "جزر كوك",
  "كوستا ريكا",
  "كوت ديفوار",
  "كرواتيا (هرفاتسكا)",
  "كوبا",
  "قبرص",
  "الجمهورية التشيكية",
  "الدنمارك",
  "جيبوتي",
  "دومينيكا",
  "جمهورية الدومينيكان",
  "تيمور الشرقية",
  "إكوادور",
  "مصر",
  "السلفادور",
  "غينيا الإستوائية",
  "إريتريا",
  "إستونيا",
  "أثيوبيا",
  "جزر فوكلاند (مالفيناس)",
  "جزر فاروس",
  "فيجي",
  "فنلندا",
  "فرنسا",
  "فرنسا متروبوليتان",
  "غيانا الفرنسية",
  "بولينيزيا الفرنسية",
  "المناطق الجنوبية لفرنسا",
  "غابون",
  "غامبيا",
  "جورجيا",
  "ألمانيا",
  "غانا",
  "جبل طارق",
  "اليونان",
  "الأرض الخضراء",
  "غرينادا",
  "جوادلوب",
  "غوام",
  "غواتيمالا",
  "غينيا",
  "غينيا - بيساو",
  "غيانا",
  "هايتي",
  "جزر هيرد وماكدونالد",
  "الكرسي الرسولي (دولة الفاتيكان)",
  "هندوراس",
  "هونغ كونغ",
  "هنغاريا",
  "أيسلندا",
  "الهند",
  "إندونيسيا",
  "إيران (جمهورية - الإسلامية)",
  "العراق",
  "أيرلندا",
  "إيطاليا",
  "جامايكا",
  "اليابان",
  "الأردن",
  "كازاخستان",
  "كينيا",
  "كيريباتي",
  "كوريا, الجمهورية الشعبية الديمقراطية",
  "جمهورية كوريا",
  "الكويت",
  "قيرغيزستان",
  "لاو , جمهورية الديمقراطية الشعبية",
  "لاتفيا",
  "لبنان",
  "ليسوتو",
  "ليبيريا",
  "الجماهيرية العربية الليبية",
  "ليختنشتاين",
  "ليتوانيا",
  "لوكسمبورغ",
  "ماكاو",
  "مقدونيا , جمهورية يوغوسلافيا السابقة",
  "مدغشقر",
  "ملاوي",
  "ماليزيا",
  "ملديف",
  "مالي",
  "مالطا",
  "جزر مارشال",
  "مارتينيك",
  "موريتانيا",
  "موريشيوس",
  "مايوت",
  "المكسيك",
  "ولايات ميكرونيزيا الموحدة",
  "جمهورية مولدوفا",
  "موناكو",
  "منغوليا",
  "مونتسيرات",
  "المغرب",
  "موزامبيق",
  "ميانمار",
  "ناميبيا",
  "ناورو",
  "نيبال",
  "هولندا",
  "جزر الأنتيل الهولندية",
  "كاليدونيا الجديدة",
  "نيوزيلاندا",
  "نيكاراغوا",
  "النيجر",
  "نيجيريا",
  "نيوي",
  "جزيرة نورفولك",
  "جزر مريانا الشمالية",
  "النرويج",
  "سلطنة عمان",
  "باكستان",
  "بالاو",
  "فلسطين",
  "بنما",
  "بابوا غينيا الجديدة",
  "باراغواي",
  "بيرو",
  "فيلبيني",
  "بيتكيرن",
  "بولندا",
  "البرتغال",
  "بورتوريكو",
  "دولة قطر",
  "جمع شمل",
  "رومانيا",
  "الاتحاد الروسي",
  "رواندا",
  "سانت كيتس ونيفيس",
  "القديسة لوسيا",
  "سانت فنسنت وجزر غرينادين",
  "ساموا",
  "سان مارينو",
  "سان تومي وبرينسيبي",
  "المملكة العربية السعودية",
  "السنغال",
  "سيشيل",
  "سيرا ليون",
  "سنغافورة",
  "سلوفاكيا (جمهورية سلوفاكيا)",
  "سلوفينيا",
  "جزر سليمان",
  "الصومال",
  "جنوب أفريقيا",
  "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
  "إسبانيا",
  "سيريلانكا",
  "سانت هيلانة",
  "سانت بيير وميكلون",
  "السودان",
  "سورينام",
  "جزر سفالبارد وجان ماين",
  "سوازيلند",
  "السويد",
  "سويسرا",
  "الجمهورية العربية السورية",
  "مقاطعة تايوان الصينية",
  "طاجيكستان",
  "جمهورية تنزانيا المتحدة",
  "تايلاند",
  "توجو",
  "توكيلاو",
  "تونغا",
  "ترينداد وتوباغو",
  "تونس",
  "ديك رومى",
  "تركمانستان",
  "جزر تركس وكايكوس",
  "توفالو",
  "أوغندا",
  "أوكرانيا",
  "الإمارات العربية المتحدة",
  "المملكة المتحدة",
  "الولايات المتحدة الأمريكية",
  "جزر الولايات المتحدة البعيدة الصغرى",
  "أوروغواي",
  "أوزبكستان",
  "فانواتو",
  "فنزويلا",
  "فيتنام",
  "جزر العذراء البريطانية)",
  "جزر فيرجن (الولايات المتحدة)",
  "جزر واليس وفوتونا",
  "الصحراء الغربية",
  "اليمن",
  "يوغوسلافيا",
  "زامبيا",
  "زمبابوي",
  "فلسطين",
];

export const Activities = [
  {
    en: "Quality & Standardization Consultants",
    ar: "استشارات الجودة والمعايرة والتقييس",
    value: "QUALITY_STANDARDIZATION_CONSULTANTS",
  },
  {
    en: "Human Resource Consultants",
    ar: "استشارات الموارد البشرية",
    value: "HUMAN_RESOURCE_CONSULTANTS",
  },
  {
    en: "Architectural & Engineering Consultancies",
    ar: "استشارات الهندسة المعمارية",
    value: "ARCHITECTURAL_ENGINEERING_CONSULTANCIES",
  },
  {
    en: "Management Consultancies",
    ar: "استشارات ودراسات إدارية",
    value: "MANAGEMENT_CONSULTANCIES",
  },
  {
    en: "Legal Consultants",
    ar: "الإستشارات القانونية",
    value: "LEGAL_CONSULTANTS",
  },
  {
    en: "Banking & Finance Consultant",
    ar: "الإستشارات المصرفية والمالية",
    value: "BANKING_FINANCE_CONSULTANT",
  },
  {
    en: "Health Insurance",
    ar: "التأمين الصحي",
    value: "HEALTH_INSURANCE",
  },
  {
    en: "Life Insurance",
    ar: "التأمين على الحياة",
    value: "LIFE_INSURANCE",
  },
  {
    en: "Accidents & Liabilities Insurance",
    ar: "التأمين من الحوادث والمسؤولية",
    value: "ACCIDENTS_LIABILITIES_INSURANCE",
  },
  {
    en: "Consumer Photograph Production",
    ar: "التصوير الفوتوغرافي",
    value: "CONSUMER_PHOTOGRAPH_PRODUCTION",
  },
  {
    en: "General Maintenance",
    ar: "الصيانة العامة",
    value: "GENERAL_MAINTENANCE",
  },
  {
    en: "Contracting of Civil Engineering Works",
    ar: "المقاولات العامة للإنشاءات المدنية",
    value: "CONTRACTING_OF_CIVIL_ENGINEERING_WORKS",
  },
  {
    en: "Specialized Vehicles Services",
    ar: "النقل بالسيارات ذات الأغراض المتخصصة",
    value: "SPECIALIZED_VEHICLES_SERVICES",
  },
  {
    en: "Project Development Consultant",
    ar: "إستشارات تطوير المشاريع",
    value: "PROJECT_DEVELOPMENT_CONSULTANT",
  },
  {
    en: "Information Technology Consultants",
    ar: "إستشارات تقنية المعلومات",
    value: "INFORMATION_TECHNOLOGY_CONSULTANTS",
  },
  {
    en: "Locks Repair",
    ar: "إصلاح الأقفال والكوالين",
    value: "LOCKS_REPAIR",
  },
  {
    en: "Heavy Duty Equipment, Machinery Repair, Operations & Maintenance",
    ar: "إصلاح المكائن والمعدات الثقيلة وصيانتها وتشغيلها",
    value: "HEAVY_DUTY_EQUIPMENT_MACHINERY_REPAIR_OPERATIONS_MAINTENANCE",
  },
  {
    en: "Computer Repair & Maintenance",
    ar: "إصلاح أجهزة الحاسب الآلي وصيانتها",
    value: "COMPUTER_REPAIR_MAINTENANCE",
  },
  {
    en: "Photocopiers Repair & Maintenance",
    ar: "إصلاح آلات ومعدات التصوير والنسخ وصيانتها",
    value: "PHOTOCOPIERS_REPAIR_MAINTENANCE",
  },
  {
    en: "Telecommunications Equipment Repair",
    ar: "إصلاح معدات وأجهزة الإتصال السلكي واللاسلكي",
    value: "TELECOMMUNICATIONS_EQUIPMENT_REPAIR",
  },
  {
    en: "Scaffolding Contracting",
    ar: "إقامة السقالات",
    value: "SCAFFOLDING_CONTRACTING",
  },
  {
    en: "Radio Programs & Audio Recordings Production",
    ar: "إنتاج البرامج الإذاعية والتسجيلات الصوتية",
    value: "RADIO_PROGRAMS_AUDIO_RECORDINGS_PRODUCTION",
  },
  {
    en: "IT Infrastructure",
    ar: "إنشاء البنية التحتية لتقنية المعلومات",
    value: "IT_INFRASTRUCTURE",
  },
  {
    en: "Painting Contracting",
    ar: "أعمال الأصباغ والدهانات",
    value: "PAINTING_CONTRACTING",
  },
  {
    en: "Plumbing & Sanitary Contracting",
    ar: "أعمال التمديدات والتركيبات الصحية",
    value: "PLUMBING_SANITARY_CONTRACTING",
  },
  {
    en: "Interior Decoration",
    ar: "أعمال تصميم و تنفيذ التصميم الداخلي",
    value: "INTERIOR_DECORATION",
  },
  {
    en: "electromechanical works",
    ar: "أعمال كهروميكانيكية",
    value: "ELECTROMECHANICAL_WORKS",
  },
  { en: "other activities", ar: "أنشطة أخرى", value: "OTHER_ACTIVITIES" },
  { en: "Cafeteria", ar: "بيع الوجبات الخفيفة", value: "CAFETERIA" },
  {
    en: "Scaffolds Rental",
    ar: "تأجير السقالات",
    value: "SCAFFOLDS_RENTAL",
  },
  { en: "Car Rental", ar: "تأجير السيارات", value: "CAR_RENTAL" },
  {
    en: "Pumps, Engines & Generators Rental",
    ar: "تأجير المضخات والمحركات والمولدات",
    value: "PUMPS_ENGINES_GENERATORS_RENTAL",
  },
  {
    en: "Tyre Fixing & Wheel Alignment Services",
    ar: "تبديل إطارات المركبات وإصلاحها",
    value: "TYRE_FIXING_WHEEL_ALIGNMENT_SERVICES",
  },
  {
    en: "Auto lube Centers",
    ar: "تبديل زيوت السيارات",
    value: "AUTO_LUBE_CENTERS",
  },
  {
    en: "furniture trade",
    ar: "تجارة اثاث و مفروشات",
    value: "FURNITURE_TRADE",
  },
  {
    en: "office furniture trade",
    ar: "تجارة الأثاث المكتبي",
    value: "OFFICE_FURNITURE_TRADE",
  },
  {
    en: "Ink & Printing Materials Trading",
    ar: "تجارة الأحبار ومواد الطباعة",
    value: "INK_PRINTING_MATERIALS_TRADING",
  },
  {
    en: "Stationery, Drawing & Writing Instruments Trading",
    ar: "تجارة الأدوات المكتبية وأدوات الكتابة والرسم",
    value: "STATIONERY_DRAWING_WRITING_INSTRUMENTS_TRADING",
  },
  {
    en: "Automatic Gates & Barries Trading",
    ar: "تجارة البوبات والحواجز الآلية",
    value: "AUTOMATIC_GATES_BARRIES_TRADING",
  },
  {
    en: "Computer Euipment Reuisites Trading",
    ar: "تجارة الحاسب الآلي و لوازمه",
    value: "COMPUTER_EUIPMENT_REUISITES_TRADING",
  },
  {
    en: "Tents, Awnings & Tarpaulin Trading",
    ar: "تجارة الخيام والمظلات والطرابيل",
    value: "TENTS_AWNINGS_TARPAULIN_TRADING",
  },
  {
    en: "Glass & Mirrors Trading",
    ar: "تجارة الزجاج والمرايا",
    value: "GLASS_MIRRORS_TRADING",
  },
  {
    en: "Flowers & Plants Trading",
    ar: "تجارة الزهور ونباتات الزينة",
    value: "FLOWERS_PLANTS_TRADING",
  },
  { en: "Juice Trading", ar: "تجارة العصائر", value: "JUICE_TRADING" },
  {
    en: "Lifts, Escalators & Spare Parts Trading",
    ar: "تجارة المصاعد والسلالم المتحركة وقطع غيارها",
    value: "LIFTS_ESCALATORS_SPARE_PARTS_TRADING",
  },
  {
    en: "Wooden Products Trading",
    ar: "تجارة المنتجات الخشبية",
    value: "WOODEN_PRODUCTS_TRADING",
  },
  {
    en: "Mobile Phones Trading",
    ar: "تجارة الهواتف المتحركة",
    value: "MOBILE_PHONES_TRADING",
  },
  {
    en: "Advertising Requisites Trading",
    ar: "تجارة الوسائل والأدوات الإعلانية",
    value: "ADVERTISING_REQUISITES_TRADING",
  },
  {
    en: "flowers & chocolates shop",
    ar: "تجارة زهور وشوكولاته",
    value: "FLOWERS_CHOCOLATES_SHOP",
  },
  {
    en: "Plant & Tree Nurseries Trading",
    ar: "تجارة شتلات الأشجار والنباتات",
    value: "PLANT_TREE_NURSERIES_TRADING",
  },
  {
    en: "Heavy Equipment & Machinery Spare Parts Trading",
    ar: "تجارة قطع غيار الآلات والمعدات الثقيلة",
    value: "HEAVY_EQUIPMENT_MACHINERY_SPARE_PARTS_TRADING",
  },
  {
    en: "Construction Equipment & Machinery Spare Parts Trading",
    ar: "تجارة قطع غيار معدات وآليات البناء",
    value: "CONSTRUCTION_EQUIPMENT_MACHINERY_SPARE_PARTS_TRADING",
  },
  {
    en: "Electrical & Electronic Appliances Spare Parts Trading",
    ar: "تجارة قطع غيارالأجهزة الكهربائية و الإلكترونية",
    value: "ELECTRICAL_ELECTRONIC_APPLIANCES_SPARE_PARTS_TRADING",
  },
  {
    en: "Air-condition, Refrigeration Spare Parts Antennas Trading",
    ar: "تجارة قطع غيارأجهزة التكييف و التبريد و مكوناتها",
    value: "AIR_CONDITION_REFRIGERATION_SPARE_PARTS_ANTENNAS_TRADING",
  },
  {
    en: "Computer & Data Processing Requisites Trading",
    ar: "تجارة مستلزمات الحاسب الآلي ومعالجة البيانات",
    value: "COMPUTER_DATA_PROCESSING_REQUISITES_TRADING",
  },
  {
    en: "Fire Fighting & Safety Equipment Trading",
    ar: "تجارة معدات و أجهزة السلامة و إطفاء الحريق",
    value: "FIRE_FIGHTING_SAFETY_EQUIPMENT_TRADING",
  },
  {
    en: "Crystal Products Trading",
    ar: "تجارة منتجات البلور (الكريستال)",
    value: "CRYSTAL_PRODUCTS_TRADING",
  },
  {
    en: "Building & Construction Materials Trading",
    ar: "تجارة مواد البناء",
    value: "BUILDING_CONSTRUCTION_MATERIALS_TRADING",
  },
  {
    en: "Computer software Trading",
    ar: "تجارة نظم الحاسب الآلي وبرامجه",
    value: "COMPUTER_SOFTWARE_TRADING",
  },
  {
    en: "Pastry Preparing",
    ar: "تحضير الفطائر والمعجنات وتجهيزها",
    value: "PASTRY_PREPARING",
  },
  {
    en: "Lifts & Escalators Contracting",
    ar: "تركيب المصاعد والسلالم المتحركة",
    value: "LIFTS_ESCALATORS_CONTRACTING",
  },
  {
    en: "Air-Condition, Ventilations, Air Filtration Systems Installations & Maintenance",
    ar: "تركيب أنظمة التكييف والتهوية وتنقية الهواء وصيانتها",
    value:
      "AIR_CONDITION_VENTILATIONS_AIR_FILTRATION_SYSTEMS_INSTALLATIONS_MAINTENANCE",
  },
  {
    en: "Fire Fighting & Safety Equipment Installation and maintenance",
    ar: "تركيب معدات السلامة وإطفاء الحريق وصيانتها",
    value: "FIRE_FIGHTING_SAFETY_EQUIPMENT_INSTALLATION_AND_MAINTENANCE",
  },
  {
    en: "Security & Survellance Systems Installation & Maintenance",
    ar: "تركيب معدات وأجهزة الأمن و المراقبة و صيانتها",
    value: "SECURITY_SURVELLANCE_SYSTEMS_INSTALLATION_MAINTENANCE",
  },
  { en: "cars repairing", ar: "تصليح سيارات", value: "CARS_REPAIRING" },
  {
    en: "Web Design",
    ar: "تصميم مواقع الشبكة المعلوماتية (الإنترنت)",
    value: "WEB_DESIGN",
  },
  {
    en: "Computer Software House",
    ar: "تصميم نظم الحاسب الآلي",
    value: "COMPUTER_SOFTWARE_HOUSE",
  },
  {
    en: "Computer Software House",
    ar: "تصميم نظم الحاسب الآلي",
    value: "COMPUTER_SOFTWARE_HOUSE",
  },
  {
    en: "Graphic Designer",
    ar: "تصميم وإنتاج الإعلانات",
    value: "GRAPHIC_DESIGNER",
  },
  {
    en: "Documentary Filming",
    ar: "تصوير الأفلام الوثائقية",
    value: "DOCUMENTARY_FILMING",
  },
  {
    en: "Parties & Private Functions Filming",
    ar: "تصوير الحفلات والمناسبات الشخصية",
    value: "PARTIES_PRIVATE_FUNCTIONS_FILMING",
  },
  {
    en: "Parties & Artistical Groups Contracts",
    ar: "تعهدات الحفلات والفرق الفنية",
    value: "PARTIES_ARTISTICAL_GROUPS_CONTRACTS",
  },
  {
    en: "Exhibition Organizing",
    ar: "تنظيم المعارض وإدارتها",
    value: "EXHIBITION_ORGANIZING",
  },
  {
    en: "Design & Artwork Services",
    ar: "خدمات التصميم الفني للمطبوعات",
    value: "DESIGN_ARTWORK_SERVICES",
  },
  {
    en: "Exterminating & Fumigating Services",
    ar: "خدمات التنظيف ومكافحة الحشرات",
    value: "EXTERMINATING_FUMIGATING_SERVICES",
  },
  {
    en: "Travel and Tourism services",
    ar: "خدمات السفر و السياحة",
    value: "TRAVEL_AND_TOURISM_SERVICES",
  },
  {
    en: "Typing & Photocopying Services",
    ar: "خدمات الطبع والنسخ",
    value: "TYPING_PHOTOCOPYING_SERVICES",
  },
  {
    en: "Cost Control & Risk Management Services",
    ar: "خدمات إدارة التكاليف والمخاطر",
    value: "COST_CONTROL_RISK_MANAGEMENT_SERVICES",
  },
  {
    en: "Quality & Standardization Certificates Issuing Services",
    ar: "خدمات إصدار شهادات الجودة والمعايرة والتقييس",
    value: "QUALITY_STANDARDIZATION_CERTIFICATES_ISSUING_SERVICES",
  },
  {
    en: "Party Security & Private Guarding Services",
    ar: "خدمات أمن الحفلات وتأمين الحراسة الخصوصية",
    value: "PARTY_SECURITY_PRIVATE_GUARDING_SERVICES",
  },
  {
    en: "Real Estate Management Services",
    ar: "خدمات تأجير العقارات وإدارتها",
    value: "REAL_ESTATE_MANAGEMENT_SERVICES",
  },
  {
    en: "translation services",
    ar: "خدمات ترجمة",
    value: "TRANSLATION_SERVICES",
  },
  {
    en: "Landscape Gardening",
    ar: "خدمات تصميم وتنفيذ الحدائق",
    value: "LANDSCAPE_GARDENING",
  },
  {
    en: "Tanks Cleaning Services",
    ar: "خدمات تنظيف الخزانات والصهاريج",
    value: "TANKS_CLEANING_SERVICES",
  },
  {
    en: "Building Cleaning Service & pest control",
    ar: "خدمات تنظيف المباني ومكافحة الحشرات",
    value: "BUILDING_CLEANING_SERVICE_PEST_CONTROL",
  },
  {
    en: "Dry Cleaning Services",
    ar: "خدمات تنظيف بالبخار",
    value: "DRY_CLEANING_SERVICES",
  },
  {
    en: "Labor Recruitment Services",
    ar: "خدمات توريد العمالة",
    value: "LABOR_RECRUITMENT_SERVICES",
  },
  {
    en: "delivery services",
    ar: "خدمات توصيل الطلبات",
    value: "DELIVERY_SERVICES",
  },
  {
    en: "Recreational Services",
    ar: "خدمات وتعهدات ترفيهية",
    value: "RECREATIONAL_SERVICES",
  },
  {
    en: "transportation service",
    ar: "خدمة مواصلات",
    value: "TRANSPORTATION_SERVICE",
  },
  {
    en: "Frame Making",
    ar: "شغل براويز الصور واللوحات الفنية",
    value: "FRAME_MAKING",
  },
  {
    en: "Cocoa & Chocolate Candies Manufacturing",
    ar: "صناعة الحلويات من الكاكاو والشيكولاته",
    value: "COCOA_CHOCOLATE_CANDIES_MANUFACTURING",
  },
  {
    en: "Medals & Shields Manufacturing",
    ar: "صناعة الميداليات والدروع",
    value: "MEDALS_SHIELDS_MANUFACTURING",
  },
  {
    en: "Generators maintenance",
    ar: "صيانة مولدات كهربائية",
    value: "GENERATORS_MAINTENANCE",
  },
  {
    en: "Commercial Publications Printing",
    ar: "طباعة المطبوعات التجارية",
    value: "COMMERCIAL_PUBLICATIONS_PRINTING",
  },
  {
    en: "Carpets Cleaning",
    ar: "غسل السجاد وتنظيفه",
    value: "CARPETS_CLEANING",
  },
  {
    en: "Car Washing & Cleaning",
    ar: "غسيل السيارات وتنظيفها",
    value: "CAR_WASHING_CLEANING",
  },
  { en: "Hotel", ar: "فندق", value: "HOTEL" },
  {
    en: "Supermarket",
    ar: "مجمع إستهلاكي (سوبرماركت)",
    value: "SUPERMARKET",
  },
  {
    en: "TV & Radio Broadcasting Station",
    ar: "محطة للبث التلفزيوني والإذاعي",
    value: "TV_RADIO_BROADCASTING_STATION",
  },
  { en: "Restaurant", ar: "مطعم", value: "RESTAURANT" },
  {
    en: "Cleaning equipment",
    ar: "معدات تنظيف",
    value: "CLEANING_EQUIPMENT",
  },
  {
    en: "Building Contracting",
    ar: "مقاولات البناء",
    value: "BUILDING_CONTRACTING",
  },
  {
    en: "Publishing of Newspapers, Magazines & Periodicals",
    ar: "نشر الصحف والمجلات والدوريات",
    value: "PUBLISHING_OF_NEWSPAPERS_MAGAZINES_PERIODICALS",
  },
  {
    en: "Aluminum workshop",
    ar: "ورشة ألمونيوم",
    value: "ALUMINUM_WORKSHOP",
  },
  {
    en: "Steel Fabrication & Welding Workshop",
    ar: "ورشة للحدادة واللحام",
    value: "STEEL_FABRICATION_WELDING_WORKSHOP",
  },
  {
    en: "Insurance Brokers",
    ar: "وسيط تأمين",
    value: "INSURANCE_BROKERS",
  },
  {
    en: "Advertising Agency",
    ar: "وكالة إعلان",
    value: "ADVERTISING_AGENCY",
  },
  {
    en: "Full Service Postal Agency",
    ar: "وكالة بريدية كاملة الخدمة",
    value: "FULL_SERVICE_POSTAL_AGENCY",
  },
];
function addLanguageToUrl(url, currentLanguage) {
  const urlParts = url?.split("/").filter(Boolean);
  if (urlParts.find((e) => e == "tmp") == "tmp") return;
  if (urlParts[0] !== "en" && urlParts[0] !== "ar") {
    urlParts.unshift(currentLanguage);
  }
  return "/" + urlParts.join("/");
}

function resolveHome(url) {
  if (url === "/en") return "/en/home";
  if (url === "/ar") return "/ar/home";
  return url;
}

function extractLanguageFromUrl(url) {
  const regExpResilt = url.match(/^\/(ar|en)\/.*$/);
  if (!regExpResilt) return "ar";
  return regExpResilt[1];
}

export async function buildCanonicalUrl(currentUrl, currentLanguage) {
  sessionStorage.removeItem("language-switch");
  // let canonicalUrl = currentUrl.toLowerCase();
  let canonicalUrl = currentUrl;
  canonicalUrl = addLanguageToUrl(canonicalUrl, currentLanguage);
  canonicalUrl = resolveHome(canonicalUrl);
  const canonicalLanguage = extractLanguageFromUrl(canonicalUrl);
  return { canonicalUrl, canonicalLanguage };
}

export async function switchLanguages() {
  const url = window.location.pathname;
  const urlParts = url.split("/").filter(Boolean);

  const currentLanguage = urlParts[0];
  const targetLanguage = currentLanguage === "en" ? "ar" : "en";

  urlParts[0] = targetLanguage;

  sessionStorage.setItem("language-switch", true);

  window.location.href = "/" + urlParts.join("/");
}
