export const CountriesLTR = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia (Hrvatska)",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "France Metropolitan",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and Mc Donald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao, People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia, The Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia (Slovak Republic)",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "St. Helena",
  "St. Pierre and Miquelon",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Yugoslavia",
  "Zambia",
  "Zimbabwe",
  "Palestine",
];

export const CountriesRTL = [
  "أفغانستان",
  "ألبانيا",
  "الجزائر",
  "ساموا الأمريكية",
  "أندورا",
  "أنغولا",
  "أنغيلا",
  "أنتاركتيكا",
  "أنتيغوا وبربودا",
  "الأرجنتين",
  "أرمينيا",
  "أروبا",
  "أستراليا",
  "النمسا",
  "أذربيجان",
  "جزر البهاما",
  "البحرين",
  "بنغلاديش",
  "بربادوس",
  "بيلاروسيا",
  "بلجيكا",
  "بليز",
  "بنن",
  "برمودا",
  "بوتان",
  "بوليفيا",
  "البوسنة والهرسك",
  "بوتسوانا",
  "جزيرة بوفيت",
  "البرازيل",
  "إقليم المحيط البريطاني الهندي",
  "بروناي دار السلام",
  "بلغاريا",
  "بوركينا فاسو",
  "بوروندي",
  "كمبوديا",
  "الكاميرون",
  "كندا",
  "الرأس الأخضر",
  "جزر كايمان",
  "جمهورية افريقيا الوسطى",
  "تشاد",
  "شيلي",
  "الصين",
  "جزيرة الكريسماس",
  "جزر كوكوس (كيلينغ)",
  "كولومبيا",
  "جزر القمر",
  "الكونغو",
  "جمهورية الكونغو الديمقراطية",
  "جزر كوك",
  "كوستا ريكا",
  "كوت ديفوار",
  "كرواتيا (هرفاتسكا)",
  "كوبا",
  "قبرص",
  "الجمهورية التشيكية",
  "الدنمارك",
  "جيبوتي",
  "دومينيكا",
  "جمهورية الدومينيكان",
  "تيمور الشرقية",
  "إكوادور",
  "مصر",
  "السلفادور",
  "غينيا الإستوائية",
  "إريتريا",
  "إستونيا",
  "أثيوبيا",
  "جزر فوكلاند (مالفيناس)",
  "جزر فاروس",
  "فيجي",
  "فنلندا",
  "فرنسا",
  "فرنسا متروبوليتان",
  "غيانا الفرنسية",
  "بولينيزيا الفرنسية",
  "المناطق الجنوبية لفرنسا",
  "غابون",
  "غامبيا",
  "جورجيا",
  "ألمانيا",
  "غانا",
  "جبل طارق",
  "اليونان",
  "الأرض الخضراء",
  "غرينادا",
  "جوادلوب",
  "غوام",
  "غواتيمالا",
  "غينيا",
  "غينيا - بيساو",
  "غيانا",
  "هايتي",
  "جزر هيرد وماكدونالد",
  "الكرسي الرسولي (دولة الفاتيكان)",
  "هندوراس",
  "هونغ كونغ",
  "هنغاريا",
  "أيسلندا",
  "الهند",
  "إندونيسيا",
  "إيران (جمهورية - الإسلامية)",
  "العراق",
  "أيرلندا",
  "إيطاليا",
  "جامايكا",
  "اليابان",
  "الأردن",
  "كازاخستان",
  "كينيا",
  "كيريباتي",
  "كوريا, الجمهورية الشعبية الديمقراطية",
  "جمهورية كوريا",
  "الكويت",
  "قيرغيزستان",
  "لاو , جمهورية الديمقراطية الشعبية",
  "لاتفيا",
  "لبنان",
  "ليسوتو",
  "ليبيريا",
  "الجماهيرية العربية الليبية",
  "ليختنشتاين",
  "ليتوانيا",
  "لوكسمبورغ",
  "ماكاو",
  "مقدونيا , جمهورية يوغوسلافيا السابقة",
  "مدغشقر",
  "ملاوي",
  "ماليزيا",
  "ملديف",
  "مالي",
  "مالطا",
  "جزر مارشال",
  "مارتينيك",
  "موريتانيا",
  "موريشيوس",
  "مايوت",
  "المكسيك",
  "ولايات ميكرونيزيا الموحدة",
  "جمهورية مولدوفا",
  "موناكو",
  "منغوليا",
  "مونتسيرات",
  "المغرب",
  "موزامبيق",
  "ميانمار",
  "ناميبيا",
  "ناورو",
  "نيبال",
  "هولندا",
  "جزر الأنتيل الهولندية",
  "كاليدونيا الجديدة",
  "نيوزيلاندا",
  "نيكاراغوا",
  "النيجر",
  "نيجيريا",
  "نيوي",
  "جزيرة نورفولك",
  "جزر مريانا الشمالية",
  "النرويج",
  "سلطنة عمان",
  "باكستان",
  "بالاو",
  "فلسطين",
  "بنما",
  "بابوا غينيا الجديدة",
  "باراغواي",
  "بيرو",
  "فيلبيني",
  "بيتكيرن",
  "بولندا",
  "البرتغال",
  "بورتوريكو",
  "دولة قطر",
  "جمع شمل",
  "رومانيا",
  "الاتحاد الروسي",
  "رواندا",
  "سانت كيتس ونيفيس",
  "القديسة لوسيا",
  "سانت فنسنت وجزر غرينادين",
  "ساموا",
  "سان مارينو",
  "سان تومي وبرينسيبي",
  "المملكة العربية السعودية",
  "السنغال",
  "سيشيل",
  "سيرا ليون",
  "سنغافورة",
  "سلوفاكيا (جمهورية سلوفاكيا)",
  "سلوفينيا",
  "جزر سليمان",
  "الصومال",
  "جنوب أفريقيا",
  "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
  "إسبانيا",
  "سيريلانكا",
  "سانت هيلانة",
  "سانت بيير وميكلون",
  "السودان",
  "سورينام",
  "جزر سفالبارد وجان ماين",
  "سوازيلند",
  "السويد",
  "سويسرا",
  "الجمهورية العربية السورية",
  "مقاطعة تايوان الصينية",
  "طاجيكستان",
  "جمهورية تنزانيا المتحدة",
  "تايلاند",
  "توجو",
  "توكيلاو",
  "تونغا",
  "ترينداد وتوباغو",
  "تونس",
  "ديك رومى",
  "تركمانستان",
  "جزر تركس وكايكوس",
  "توفالو",
  "أوغندا",
  "أوكرانيا",
  "الإمارات العربية المتحدة",
  "المملكة المتحدة",
  "الولايات المتحدة الأمريكية",
  "جزر الولايات المتحدة البعيدة الصغرى",
  "أوروغواي",
  "أوزبكستان",
  "فانواتو",
  "فنزويلا",
  "فيتنام",
  "جزر العذراء البريطانية)",
  "جزر فيرجن (الولايات المتحدة)",
  "جزر واليس وفوتونا",
  "الصحراء الغربية",
  "اليمن",
  "يوغوسلافيا",
  "زامبيا",
  "زمبابوي",
  "فلسطين",
];
